//
//  SearchKeywords.swift
//  Dinecraft
//
//  Created by Ethan Fitzgerald on 15/5/2022.
//

import Foundation

class Keywords {
    //Properties
    
    
    //Variables
    
    
    //References
    
    
    //Data
    let fruits = [
      "Apple",
      "Apricot",
      "Avocado",
      "Banana",
      "Berries",
      "Breadfruit",
      "Carob",
      "Cherry",
      "Citron",
      "Coconut",
      "Date",
      "Dragon Fruit",
      "Durian",
      "Fig",
      "Ginger",
      "Grape",
      "Currant",
      "Raisin",
      "Grapefruit",
      "Guava",
      "Jackfruit",
      "Jujube",
      "Kiwifruit",
      "Kumquat",
      "Lemon",
      "Lime",
      "Longan",
      "Loquat",
      "Lucuma",
      "Lychee",
      "Mamey Sapote",
      "Mango",
      "Mangosteen",
      "Melons",
      "Nance",
      "Nectarine",
      "Noni",
      "Oranges",
      "Mandarin",
      "Navel",
      "Seville",
      "Valencia",
      "Papaya",
      "Passion Fruit",
      "Peach",
      "Pear",
      "Asian Pear",
      "Persimmon",
      "Pineapple",
      "Plantain",
      "Plum",
      "Damson",
      "Prunes",
      "Pomegranate",
      "Pomelo",
      "Quince",
      "Rambutan",
      "Rhubarb",
      "Starfruit",
      "Tamarillo",
      "Tamarind",
      "Tangerine",
      "Tangelo",
      "Tomato",
    ]
    
    let vegetables = [
        "Artichoke",
        "Arugula",
        "Asparagus",
        "Avocado",
        "Bamboo",
        "Bean",
        "Beet",
        "Broccoli",
        "Brussel",
        "Cabbage",
        "Calabash",
        "Capers",
        "Carrot",
        "Cauliflower",
        "Celery",
        "Celtuce",
        "Chayote",
        "Corn",
        "Cucumber",
        "Gherkin",
        "Edamame",
        "Endive",
        "Escarole",
        "Fennel",
        "Fiddlehead",
        "Galangal",
        "Garlic",
        "Ginger",
        "Kale",
        "Kohlrabi",
        "Mustard",
        "Rapini",
        "Spinach",
        "Horseradish",
        "Jícama",
        "Kale",
        "Curly",
        "Lacinato",
        "Ornamental",
        "Kohlrabi",
        "Leeks",
        "Lemongrass",
        "Lettuce",
        "Iceberg",
        "Romaine",
        "Lotus",
        "Mushroom",
        "Nopales",
        "Okra",
        "Olive",
        "Onion",
        "Parsley",
        "Parsnip",
        "Peas",
        "Pepper",
        "Plantain",
        "Potato",
        "Pumpkin",
        "Purslane",
        "Radicchio",
        "Radish",
        "Rutabaga",
        "Shallots",
        "Spinach",
        "Squash",
        "Swiss Chard",
        "Taro",
        "Tomatillo",
        "Tomato",
        "Turnip",
        "Watercress",
        "Yams",
        "Zucchini"
    ]
}
